### ISSUE TITLE
npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by AJohnJones** [AndersonMamede/electron-progressbar#1]
npm install electron-progressbar --save

the above command gives me a 404 issue

**Comment by AndersonMamede** [comment]
Sorry but I had to pause the development for some days but now everything's back to normal and it's going to be released in a few days, I just need to finish some minor details.

I've updated the README.md to state that is not ready yet.

Thank you.

**Comment by AndersonMamede** [comment]
The component is now published on npm:
https://www.npmjs.com/package/electron-progressbar

To install it on your project:
npm install electron-progressbar --save

You can read the documentation here on GitHub or on NPM.
