### ISSUE TITLE
How to use remote BrowserWindow

### ISSUE THREAD

**Issue by flaushi** [AndersonMamede/electron-progressbar#11]
Hey, 
I want to create a progress bar from a script that is loaded inside my html. So, I think I have to use the `electron.remote.BrowserWindow`.
In the source, 
https://github.com/AndersonMamede/electron-progressbar/blob/56ed56a1b7ef9c5f3e21a81091d0233822619b80/source/index.js#L3
however, the `electron.BrowserWindow` is imported.

**Comment by stefanDeveloper** [comment]
Got stuck on the same problem...

Currently I'm trying to use the electron-progressbar in my ipcRenderer function.
For some reason I cannot set my my remote.BrowserWindow as the BrowserWindow of my ProgressBar

```
ipcRenderer.on('test', (event) => {
  let win = remote.getCurrentWindow();
  const progressbar = new ProgressBar({
    indeterminate: false,
    text: 'Preparing data...',
    detail: 'Wait',
    browserWindow: remote.BrowserWindow
  });

});
```
 
I receive `Uncaught TypeError: BrowserWindow is not a constructor`

**Comment by AndersonMamede** [comment]
Closing this as PR #12 was merged.

Thank you all for the contribution!
