### ISSUE TITLE
Using with Electron-updater

### ISSUE THREAD

**Issue by twigs67** [AndersonMamede/electron-progressbar#18]
Hello,

I'm trying to get this to work with Electron updater, but can't get it to work. I was hoping you might have some suggestions. I have gotten it to work with the examples you provided, but not with the updater. 

```
// updater.js
const {dialog, BrowserWindow, ipcMain} = require('electron');
const {autoUpdater} = require('electron-updater');
const ProgressBar = require('electron-progressbar');

// Enable logging
autoUpdater.logger = require('electron-log');
autoUpdater.logger.transports.file.level = 'info';

// Disable auto downloading
autoUpdater.autoDownload = false;

// Check for updates
exports.check = () => {
  // Start update check

  // autoUpdater.checkForUpdates();
  //
  // // Listen for download (update) found
  // autoUpdater.on('update-available', () => {
    // Promt user to update
    dialog.showMessageBox({
      type: 'info',
      title: 'Update Available',
      message: 'A new version is available.  Do you want to update now?',
      button: ['Update', 'No']
    }, (buttonIndex) => {

      // If not 'Update' button, return
      if (buttonIndex !== 0) return

      // Else start download and show download progress in new window
      autoUpdater.downloadUpdate();

      // Create progress window
      let progressWin = new ProgressBar({
        indeterminate: false,
        text: 'This will take a moment.',
        detail: 'Downloading',
        browserWindow: {
          webPreferences: {
            nodeIntegration: true
          }
        }
      });

      progressWin.on('completed', function () {
        console.info(`completed...`);
        progressWin.detail = 'Download complete!';
      })
          .on('aborted', function (value) {
            console.info(`aborted... ${value}`);
          })

      // Listen for progress request from progressWin
      ipcMain.on('download-progress-request', (e) => {
        console.log('download-progress-request', progressWin.value);
        e.returnValue = progressWin.value;
      });

      // Track download progress on autoUpdater
      autoUpdater.on('download-progress', (d) => {
        console.log('download-progress', d.percent);
        progressWin.value += d.percent * 100;
        progressWin.detail = `${progressWin.value} out of ${progressWin.getOptions().maxValue}...`;
      })

      // Listen for completed update download
      autoUpdater.on('update-downloaded', () => {
        console.log('update-download', progressWin.isCompleted());
        // Close progressWin
        if (progressWin && progressWin.isCompleted()) progressWin.setCompleted();

        // Promt user to quit and install update
        dialog.showMessageBox({
          type: 'info',
          title: 'Update Ready',
          message: 'A new version is ready. Quit and install now?',
          buttons: ['Yes', 'Later']
        }, (buttonIndex) => {

          // Update if 'Yes'
          if (buttonIndex === 0) autoUpdater.quitAndInstall();
        })
      })
    })
  // })
}
```

Any help would be appreciated.

**Comment by hmpargi** [comment]
> Hello,
> 
> I'm trying to get this to work with Electron updater, but can't get it to work. I was hoping you might have some suggestions. I have gotten it to work with the examples you provided, but not with the updater.
> 
> ```
> // updater.js
> const {dialog, BrowserWindow, ipcMain} = require('electron');
> const {autoUpdater} = require('electron-updater');
> const ProgressBar = require('electron-progressbar');
> 
> // Enable logging
> autoUpdater.logger = require('electron-log');
> autoUpdater.logger.transports.file.level = 'info';
> 
> // Disable auto downloading
> autoUpdater.autoDownload = false;
> 
> // Check for updates
> exports.check = () => {
>   // Start update check
> 
>   // autoUpdater.checkForUpdates();
>   //
>   // // Listen for download (update) found
>   // autoUpdater.on('update-available', () => {
>     // Promt user to update
>     dialog.showMessageBox({
>       type: 'info',
>       title: 'Update Available',
>       message: 'A new version is available.  Do you want to update now?',
>       button: ['Update', 'No']
>     }, (buttonIndex) => {
> 
>       // If not 'Update' button, return
>       if (buttonIndex !== 0) return
> 
>       // Else start download and show download progress in new window
>       autoUpdater.downloadUpdate();
> 
>       // Create progress window
>       let progressWin = new ProgressBar({
>         indeterminate: false,
>         text: 'This will take a moment.',
>         detail: 'Downloading',
>         browserWindow: {
>           webPreferences: {
>             nodeIntegration: true
>           }
>         }
>       });
> 
>       progressWin.on('completed', function () {
>         console.info(`completed...`);
>         progressWin.detail = 'Download complete!';
>       })
>           .on('aborted', function (value) {
>             console.info(`aborted... ${value}`);
>           })
> 
>       // Listen for progress request from progressWin
>       ipcMain.on('download-progress-request', (e) => {
>         console.log('download-progress-request', progressWin.value);
>         e.returnValue = progressWin.value;
>       });
> 
>       // Track download progress on autoUpdater
>       autoUpdater.on('download-progress', (d) => {
>         console.log('download-progress', d.percent);
>         progressWin.value += d.percent * 100;
>         progressWin.detail = `${progressWin.value} out of ${progressWin.getOptions().maxValue}...`;
>       })
> 
>       // Listen for completed update download
>       autoUpdater.on('update-downloaded', () => {
>         console.log('update-download', progressWin.isCompleted());
>         // Close progressWin
>         if (progressWin && progressWin.isCompleted()) progressWin.setCompleted();
> 
>         // Promt user to quit and install update
>         dialog.showMessageBox({
>           type: 'info',
>           title: 'Update Ready',
>           message: 'A new version is ready. Quit and install now?',
>           buttons: ['Yes', 'Later']
>         }, (buttonIndex) => {
> 
>           // Update if 'Yes'
>           if (buttonIndex === 0) autoUpdater.quitAndInstall();
>         })
>       })
>     })
>   // })
> }
> ```
> 
> Any help would be appreciated.

I am also looking for the same, did you able to figure out ?

**Comment by qhkm** [comment]
I manage to get it to work with electron-updater. I will share how i did it later on.

**Comment by bagas-insani** [comment]
> I manage to get it to work with electron-updater. I will share how i did it later on.

Do you mind sharing your code? Thank you.

**Comment by pedro-surf** [comment]
Also struggling to implement that.

**Comment by dyros26** [comment]
`let progressBar;

autoUpdater.on('checking-for-update', () => {
     // your code here
});

autoUpdater.on('update-available', (info) => {
     dialog.showMessageBox({
        type: 'info',
        title: 'Found Updates',
        message: 'New updates are available, do you want update now?',
        defaultId: 0,
        cancelId: 1,
        buttons: ['Yes', 'No']
    }).then(result => {
        if (result.response === 0) {

            autoUpdater.downloadUpdate();

            progressBar = new ProgressBar({
                indeterminate: false,
                title: 'Update in progress',
                text: 'Preparing to download updates.',
                detail: 'Downloading...',
                browserWindow: {
                    webPreferences: {
                        nodeIntegration: true
                    }
                }
            });
        
            progressBar.on('completed', function() {
                progressBar.detail = 'Download completed.';
            }).on('aborted', function(value) {
                sendStatusToWindow('Download aborted.');
            }).on('progress', function(value) {
                progressBar.text = 'Downloading updates.';
                progressBar.detail = `Downloading... ${value}%`;
            });
        } else if (result.response === 1) {
            changeUpdaterMenu({ label: 'Check for updates', enabled: true });
        }
    });
});

autoUpdater.on('update-not-available', (info) => {
    dialog.showMessageBox({
        title: 'No Updates',
        message: 'Current version is up-to-date.'
    });
});

autoUpdater.on('download-progress', (progressObj) => {
    progressBar.value = parseInt(progressObj.percent);
});

autoUpdater.on('update-downloaded', (info) => {
    dialog.showMessageBox({
        title: 'Install Updates',
        message: 'Updates are ready to be installed.',
        defaultId: 0,
        cancelId: 1,
        buttons: ['Install and restart', 'Close']
    }).then(result => {
        if (result.response === 0) {
            setImmediate(() => autoUpdater.quitAndInstall());
        }
    });
});
`
