### ISSUE TITLE
When text set Asia character show two arrow.

### ISSUE THREAD

**Issue by chouch0u** [AndersonMamede/electron-progressbar#22]
When set Asia character as progressbar text it will show like below. I hope can change some css style.
![image](https://user-images.githubusercontent.com/4880734/104710764-6d295d80-575b-11eb-9877-a21c90b40b59.png)

**Comment by DavidDolyak** [comment]
Having the same issue!

**Comment by CherryPetale** [comment]
```javascript
new ProgressBar({
  text: "日本語",
  style: {
    text: {
      overflow: "hidden" // add this code
    }
  }
});
```
