### ISSUE TITLE
Progress bar details not being displayed other than window title

### ISSUE THREAD

**Issue by lalanankit** [AndersonMamede/electron-progressbar#23]
I have been trying to show a progress-bar window with the codes that are provided in the readme document. Unfortunately, I am not able to get the htmlcontent of the progressbar in the window.
Here is a snippet of code:

`const { app, BrowserWindow, ipcMain, Notification, dialog, ipcRenderer, Menu, shell, session } = require('electron');
const ProgressBar = require('electron-progressbar');`

`let loginWindow, progressBar;`

```
async function createWindow() {
    loginWindow = new BrowserWindow({
        width: constantData.size.loginScreen.width,
        height: constantData.size.loginScreen.height,
        icon: path.join(__dirname, 'public/icon/favicon.ico'),
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            enableRemoteModule: true
        }
    });

    loginWindow.once('ready-to-show', () => {
        autoUpdater.checkForUpdatesAndNotify();
    });

    var cookieResults = await getCookies();
    await loginWindow.loadFile(path.join(__dirname, 'src\\view\\index.html'),
        {
            query: {
                "cookie": cookieResults
            }
        });
        showProgressbar(loginWindow);
}
```

```
ipcMain.on('show-progressbar', showProgressbar);
ipcMain.on('set-progressbar-completed', setProgressbarCompleted);
```

```
function showProgressbar(window = dashboardWindow) {
    if (progressBar) {
        return;
    }

    progressBar = new ProgressBar({
        text: 'Preparing data...',
        detail: 'Wait...',
        text: 'Preparing to fetching your data for the initial load',
        browserWindow: {
            parent: window,
            webPreferences: {
                nodeIntegration: true
            }
        }
    });

    progressBar
        .on('completed', function () {
            progressBar.detail = 'Task completed. Exiting...';
            progressBar = null;
        });
}`

function setProgressbarCompleted() {
    if (progressBar) {
        progressBar.setCompleted();
    }
}

```
`app.on('ready', () => {
    createWindow();
});`

Here is the UI:
![image](https://user-images.githubusercontent.com/71725903/114179047-3b8cf080-995e-11eb-93ac-8465756e1c0c.png)

**Comment by kzimny** [comment]
I have the same issue. @lalanankit : do you build your app with webpack v4 or v5?

**Comment by lalanankit** [comment]
This is replicated when debugging and I’m not sure what do you mean by building with webpack version? Apologies!

Sent from my iPhone

On Apr 13, 2021, at 11:18 PM, Krzysztof Zimny ***@***.***> wrote:

﻿

I have the same issue. @lalanankit<https://github.com/lalanankit> : do you build your app with webpack v4 or v5?

**Comment by kzimny** [comment]
How do you compile your solution for production? With webpack? The issue on my side is since I changed the version of webpack from v4 to v5. Thx.

**Comment by lalanankit** [comment]
For the production, I’m using electron-packer for packaging, building and distribution. Usually, I run this on vscode using electron ./app.js.

I have debugged this package, I found out that the ‘did-finish-loading’ does not fire up to load the htmlcontents. Wonder, if the author responds to the issue.


Sent from my iPhone

On Apr 13, 2021, at 11:33 PM, Krzysztof Zimny ***@***.***> wrote:

﻿

How do you compile your solution for production? With webpack? The issue on my side is since I changed the version of webpack from v4 to v5. Thx.

**Comment by gnudeep** [comment]
I also face the same issue.

npm: '7.9.0'
node: '15.12.0'
electron-progressbar@2.0.0

**Comment by kzimny** [comment]
For Electron version 12 and above when creating BrowserWindow additional settings are required: 
```
contextIsolation: false, 
enableRemoteModule: true,
```

```
new BrowserWindow({
	width: 500, 
	height: 170,
	webPreferences: {
		nodeIntegration: true,
		contextIsolation: false,
		enableRemoteModule: true,
	}
});
```

**Comment by lalanankit** [comment]
Adding the additional lines has solved the issue. Thank you @kzimny 
The snipped of full code for the object- 
```
progressBar = new ProgressBar({
        text: 'Preparing data...',
        detail: 'Wait...',
        text: 'Fetching your details',
        browserWindow: {
            parent: window,
            modal: true,
            resizable: false,
            closable: false,
            minimizable: false,
            maximizable: false,
            width: 500,
            icon: path.join(__dirname, 'public/icon/favicon.ico'),
            height: 170,
            webPreferences: {
                nodeIntegration: true,
                contextIsolation: false,
                enableRemoteModule: true
            },
        },
    });
```
![image](https://user-images.githubusercontent.com/71725903/114871201-c23b4500-9e18-11eb-8016-0348ebbfb164.png)

**Comment by jjeff** [comment]
FWIW, I think `enableRemoteModule: true` is not needed. 

It doesn't look like electron-progressbar uses electron.remote functionality (which is deprecated anyway).

**Comment by AndersonMamede** [comment]
Hey guys, electron-progressbar v2.0.1 has just been released with a patch to fix this issue (`contextIsolation` now defaults to `false`). Thanks a lot! :)
