### ISSUE TITLE
It does not work properly with Electron 12

### ISSUE THREAD

**Issue by janosvajda** [AndersonMamede/electron-progressbar#25]
Hi, 

Today morning I upgraded my codebase from Electron 11 to the latest Electron 12 (12.0.7) and noticed an issue. 

When Progress dialogue shows, but the progress bar is disappeared from the dialogue. 

I use customized style so I removed It but did not solve the issue.

I removed each parameters so I have now only this code:

`  let progressBar = new ProgressBar({
    text: 'File uploading',
    detail: 'Please wait...'
  });`

but it is the same, unfortunately, does not solve the problem.

If I roll back the code to Electron 11 then It works so It seems to be an Electron 12 related issue.

**Comment by janosvajda** [comment]
I investigated this and fixed it in my project. 

Progressbar's class window's options web preference part should get this parameter: `contextIsolation: false` because in Electron 12 context isolation is ON by default.

**Comment by AndersonMamede** [comment]
electron-progressbar v2.0.1 has just been released with a patch to fix this issue. Thanks a lot @janosvajda !
