### ISSUE TITLE
Progressbar is working fine before creating exe of app ,after exe generated it seems blank

### ISSUE THREAD

**Issue by Nrkapadia** [AndersonMamede/electron-progressbar#29]
electron version : 17.0.0
electron-progressbar : 2.0.1
![image](https://user-images.githubusercontent.com/75656940/222733080-c52888d4-4aae-46fc-99e0-56d278c5872b.png)
The code for generating this is basic as described in npm package same.
This code works fine in debug mode of our app but when we create final exe of that it shows this blank screen.

**Comment by AndersonMamede** [comment]
You can try enabling the `debug` option to troubleshoot the progress bar window. This will automatically open the DevTools panel of the progress bar window, allowing you to inspect the elements and check for any errors, messages, or unusual behavior in the console. Other than that, we would need some logs, debug information, or error messages to be able to do some debugging.

Example:
```js
  var progressBar = new ProgressBar({
    debug: true, // enable DevTools panel
    text: 'Preparing data...',
    detail: 'Wait...',
    // etc
  });
```

Feel free to reopen this issue if you have any additional logs or debugging information to share, require more information from us, or if you're able to resolve the issue on your own.

**Comment by AndersonMamede** [comment]
By the way, are you using webpack when creating the final exe? If so, maybe you can try making this change and check the outcome: https://github.com/AndersonMamede/electron-progressbar/compare/master...jl4386:electron-progressbar:master

If that fixes the issue, please let me know and I will try adding it to the project.
