### ISSUE TITLE
Include electron-progressbar in project and app's package size increased

### ISSUE THREAD

**Issue by hfxu** [AndersonMamede/electron-progressbar#3]
Hi
My electron application package size was 60M originally , but after the import `electron-progressbar`, the packet size increased to 109M.
I found the `dependencies` of  `electron-progressbar`  is :
```javascript
"dependencies": {
    "extend": "^3.0.1",
    "electron": "^1.7.5"
}
```
Is `electron` is the necessary dependency of this module?
When I edit the `package.json` of this module, set `electron` as a `devDependencies` of this module, the app pkg size was decreased.

**Comment by AndersonMamede** [comment]
Hi there hfxu!

`electron` is not really necessary as a `dependency`. We had PR #2  and moved it to `devDependencies` but the npm package wasn't updated yet (now it is!). So you can just move it do `devDependencies` too.

Thank you!! :smile:
