### ISSUE TITLE
How to load image in electron-progressbar?

### ISSUE THREAD

**Issue by oinochoe** [AndersonMamede/electron-progressbar#30]
I found `htmlContent` image load and update. but not working. please tell me why?

**Comment by AndersonMamede** [comment]
@oinochoe You should be able to use any HTML element in the progressbar, you just need to set the HTML code to property `text`, as if it were `htmlContent`, like this:

```js
  var progressBar = new ProgressBar({
    text: 'Preparing data. Example of image:<br><img src="https://picsum.photos/seed/picsum/400/300">',
    detail: 'Wait...'
  });
```

**Comment by oinochoe** [comment]
> @oinochoe You should be able to use any HTML element in the progressbar, you just need to set the HTML code to property `text`, as if it were `htmlContent`, like this:
> 
> 
> 
> ```js
> 
>   var progressBar = new ProgressBar({
> 
>     text: 'Preparing data. Example of image:<br><img src="https://picsum.photos/seed/picsum/400/300">',
> 
>     detail: 'Wait...'
> 
>   });
> 
> ```

Thanks.
However, I want to use a local image with relative path.
How can I use the image?

**Comment by AndersonMamede** [comment]
For local images you can try to set the `src` with prefix `file://path-to-local-image` or maybe use a [base64 encoded image](https://stackoverflow.com/a/8499716), for example:

```js
  var image = "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==";

  var progressBar = new ProgressBar({
    text: `Preparing data. Example of image:<br><img src="data:image/png;base64,${image}">`,
    detail: 'Wait...'
  });
```

**Comment by oinochoe** [comment]
> For local images you can try to set the `src` with prefix `file://path-to-local-image` or maybe use a [base64 encoded image](https://stackoverflow.com/a/8499716), for example:
> 
> ```js
>   var image = "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==";
> 
>   var progressBar = new ProgressBar({
>     text: `Preparing data. Example of image:<br><img src="data:image/png;base64,${image}">`,
>     detail: 'Wait...'
>   });
> ```

Thanks sincerely.
