### ISSUE TITLE
Whole Script stops after bar is completed

### ISSUE THREAD

**Issue by NyboTV** [AndersonMamede/electron-progressbar#37]
Hi. Im using this Module with TouchPortal API and after the Progressbar completed the plugin goes further until The TouchPortal API connected. then the Script just stops.  if i disable the bar it works again

**Comment by AndersonMamede** [comment]
Hi @NyboTV, to better understand and address the issue you're facing, can you please share a minimal, reproducible example of your source code?

**Comment by NyboTV** [comment]
Uhm.... Kinda difficult...

Main File:
"await AutoUpdate" 

AutoUpdate.js
download file -> show in progressbar -> after finish close Progressbar -> continue in main file.

Then the main file continues, after the last line of code where the script should wait until something changes in an tmp json file, it just closes / exits

But there are some loops and other functions that should run after that. But it just exits

it is pretty difficult to explain...

if i remove the line "progressbar.close()" or "progressbar.isCompleted" the script just waits at the last line, like it should. But the Progressbar is still there. But with the lines, it closes

i hope this english is good enough to understand

**Comment by AndersonMamede** [comment]
Hi @NyboTV, without being able to reproduce the issue or seeing the exact code, it's challenging to pinpoint the reason for this behavior and help with it. Please refer to this working example that uses autoUpdater with the progress bar and try to implement in a similar way: https://github.com/AndersonMamede/electron-progressbar/issues/18#issuecomment-740520140
