### ISSUE TITLE
How to implement progress bar for electron auto updater download progress

### ISSUE THREAD

**Issue by orizzontiholding** [AndersonMamede/electron-progressbar#38]
How I can implement the progress bar to track the autoUpdater module of electron progress?I've done some tests and I'm unable to get it working correctly, the progress bar if called inside the update-progress event will be opened multiple times. 

any suggestion will be appreciated.
Thank you

**Comment by AndersonMamede** [comment]
Hi @orizzontiholding, it's challenging to pinpoint the exact reason for this behavior without seeing the exact code, but I suppose it's all about instantiating and updating the progress bar on the right places/events. You can find a working example for that on this comment: https://github.com/AndersonMamede/electron-progressbar/issues/18#issuecomment-740520140

**Comment by orizzontiholding** [comment]
> Hi @orizzontiholding, it's challenging to pinpoint the exact reason for this behavior without seeing the exact code, but I suppose it's all about instantiating and updating the progress bar on the right places/events. You can find a working example for that on this comment: [#18 (comment)](https://github.com/AndersonMamede/electron-progressbar/issues/18#issuecomment-740520140)

Ok, thank you. I will take a look to the example you've linked to setup the progressbar inside my electron app.

**Comment by orizzontiholding** [comment]
@AndersonMamede I've tested the suggested implementation, but I will not see the progress bar, the window where is supposed that the progress bar will appera, will remain blank. Here is my code

```js
autoUpdater.on('update-available', () => {
        dialog.showMessageBox({
            type: 'question',
            title: 'DocRif updater',
            message: "Una nuova versione del programma è disponibile, vuoi installare l'aggiornamento?",
            buttons: ['Si', 'No']
    }).then( (buttonIndex) => {
        console.log( buttonIndex )
        if (buttonIndex.response === 0) {
            autoUpdater.downloadUpdate()
        }

        progressbar = new ProgressBar({
            indeterminate: false,
            title: 'Aggiornamento in corso',
            text: 'Download degli aggiornamenti in corso',
            detail: 'Download in corso...',
        })
    }).catch( e => console.log(e) )
})
//
autoUpdater.on('update-not-available', () => {
    dialog.showMessageBox({
        type: 'info',
        title: 'DocRif updater',
        message: 'La versione corrente del programma è aggiornata.'
    })
})
progressbar.on('completed', () => {
    progressbar.detail = 'Download completato';
}).on('aborted', (value) => {
    console.log(value)
}).on('progress', (value) => {
    progressbar.text = 'Download aggiornamento in corso...'
    progressbar.detail = value
})
//
autoUpdater.on('download-progress', (progressObj) => {
    console.dir(progressObj)
    progressbar.value = parseInt(progressObj.percent);
});
//
autoUpdater.on('update-downloaded', () => {
    dialog.showMessageBox({
        type: 'info',
        title: 'DocRif updater',
        message: "Download aggiornamento completato. L'applicazione verrà chiusa per installare l'update."
    }).then( () => {
        setImmediate( () => { 
            console.log('Installazione aggiornamento in corso...')
            autoUpdater.quitAndInstall() 
        })
    }).catch( e => console.log(e) )
})
```

Maybe I'm doing something in a wrong way?

**Comment by orizzontiholding** [comment]
**UPDATE**

It seems that it will take a bit to show the progress bar during the updates download. Finally I have implemented it in the correct way and seems working fine. 
Thank you for the support @AndersonMamede

**Comment by AndersonMamede** [comment]
@orizzontiholding I'm glad you got it working! :slightly_smiling_face: :rocket:
