### ISSUE TITLE
Browser window is not a constructor

### ISSUE THREAD

**Issue by holidaycottages** [AndersonMamede/electron-progressbar#5]
Hello, might just be me and my lack of electron knowledge but I am trying to fire a progress bar on the click of a button.

Passing in the app or not I get

"Browser window is not a constructor"

Can you help me with an example firing the progress bar on a click event?

As all the examples just show it when the app loads

**Comment by AndersonMamede** [comment]
Hi there!

I've just created an example for you with buttons to show/hide the progressbar.

In case you can't make it work, please paste your code here so I can take a look.

main.js:
```javascript
const {app, BrowserWindow, ipcMain} = require('electron');
const ProgressBar = require('electron-progressbar');

let mainWindow;
let progressBar;

function loadApp () {
  mainWindow = new BrowserWindow({
    width : 300,
    height : 200
  });
  
  mainWindow.loadURL(`file://${__dirname}/test_page.html`);
};

function showProgressbar () {
  if (progressBar) {
    return;
  }
  
  progressBar = new ProgressBar({
    text: 'Preparing data...',
    detail: 'Wait...'
  });
  
  progressBar
    .on('completed', function() {
      progressBar.detail = 'Task completed. Exiting...';
      progressBar = null;
    });
  
  // launch the task...
  // launchTask();
}

function setProgressbarCompleted () {
  if (progressBar) {
    progressBar.setCompleted();
  }
}

function init () {
  loadApp();
  
  ipcMain.on('show-progressbar', showProgressbar);
  
  ipcMain.on('set-progressbar-completed', setProgressbarCompleted);
}

app.on("ready", init);
```

test_page.html:
```html
<!DOCTYPE html>
<html>
	<head>
		<title>Test</title>
	</head>
	<body>
		<div style="text-align:center">
			Test page<br><br>
			<button id="show-progressbar">Show progressbar</button><br><br>
			<button id="set-progressbar-completed">Set progressbar completed</button>
		</div>
		<script>
			const ipc = require('electron').ipcRenderer;
			
			document.querySelector('#show-progressbar').addEventListener('click', function(){
				ipc.send('show-progressbar');
			});
			
			document.querySelector('#set-progressbar-completed').addEventListener('click', function(){
				ipc.send('set-progressbar-completed');
			});
		</script>
	</body>
</html>
```

**Comment by holidaycottages** [comment]
Thank you so much. Got it working.

I have changed it so I can pass in a maxValue, which works, but then I added another function to update the progress, as in my button on click it loops around processing some images, I want to update the progress bar when each one is complete, currently it just pops up and says Wait... as per the setup and then disappears when the loop is done.

Any ideas?

**Comment by holidaycottages** [comment]
I know the issue, how do I pass a value from the ipc renderer function back to the main via the ipc.on call?

**Comment by holidaycottages** [comment]
Worked it out, wasnt reading properly

**Comment by AndersonMamede** [comment]
You can pass [multiple parameters to the send function](https://electronjs.org/docs/api/ipc-renderer#ipcrenderersendchannel-arg1-arg2-):

```javascript
ipc.send('set-progressbar-value', {value:9});
```

And then you can set the progress bar's value like this (inside your "main.js", for example):
```javascript
progressBar.value = x;
```

**Comment by AndersonMamede** [comment]
Glad you got it working! =)
