### ISSUE TITLE
ProgressBar window is not reusable after a progress completion

### ISSUE THREAD

**Issue by iwuvjhdva** [AndersonMamede/electron-progressbar#7]
Have to close it an create a new one in case of multiple actions that require progress indication.

**Comment by AndersonMamede** [comment]
As per design, the progress bar gets unusable after its completion (prevent old listeners/events from firing).

I'm not sure that I understand what you're trying to achieve. Could you explain a little more? Maybe show some code/example?

**Comment by AndersonMamede** [comment]
Closed until more information is provided.
